baseURL = "https://corinnefreer.com/"
languageCode = "en-us"
title = "Saderra Starter"




[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML"]

[module]

[[module.imports]]
path = "github.com/saderra/hugo-modules/starter"

[[module.imports]]
path = "github.com/saderra/hugo-modules/uitheme"

[[module.imports]]
path = "github.com/saderra/hugo-modules/alpinejs"

[[module.imports]]
path = "github.com/saderra/hugo-modules/turbolinks"

[[module.imports]]
path = "github.com/saderra/hugo-modules/netlifycms"

[[module.imports]]
path = "github.com/saderra/hugo-modules/breadcrumbs"

[[module.imports]]
path = "github.com/saderra/hugo-modules/blogtools"


[build]
writeStats = true    